### ISSUE TITLE
How do I get started with testing this?

### ISSUE THREAD

**Issue by peterennis** [gms1/node-sqlite3-orm#19]
I am new to using SQLite. What are the first steps to getting started?
When I know what I am doing I can provide a PR for the getting started doc that could also help others.
My initial goal is to investigate using SQLite with Ionic using promises/observables...

**Comment by gms1** [comment]
I would recommend by cloning this repo and playing with the provided tests

*  install global dependencies

```shell
npm -g i gulp-cli
```

*  clone the repo and install dependencies

```shell
gms@work:~/tmp$ git clone git@github.com:gms1/node-sqlite3-orm.git
gms@work:~/tmp$ cd node-sqlite3-orm/
gms@work:~/tmp/node-sqlite3-orm$  npm i
```

* build and run all tests

```shell
gms@work:~/tmp/node-sqlite3-orm$ gulp test
```

* build and run a single tests

```shell
gms@work:~/tmp/node-sqlite3-orm$ gulp build
gms@work:~/tmp/node-sqlite3-orm$ ./node_modules/.bin/jasmine dist/spec/BaseDAO.spec.js
```

* try to make changes to the tests to get familar with the code

thank you for your interest
Guenter

**Comment by gms1** [comment]
one thing I have forgotten to mention, the API-docs can be generated using "npm run typedoc" 
see 'docs / typedoc / index.html' afterwards

**Comment by peterennis** [comment]
Fixed in PR #22 

I will look into the docs next.

**Comment by peterennis** [comment]
Updated getting started with doc generation

https://github.com/gms1/node-sqlite3-orm/pull/23/files

This PR: #23

**Comment by peterennis** [comment]
Make line spacing consistent in src.

Fixed in #24

**Comment by peterennis** [comment]
Not sure where the red x is from. All checks pass.
There was a Travis failure with white space that I fixed but it seems not to clear the error.

![capture204](https://user-images.githubusercontent.com/140737/31572762-0573ab1c-b062-11e7-9b30-9f845d2f4866.png)

**Comment by gms1** [comment]
the mentioned error occurred because tslint found trailing whitespaces:
see
https://travis-ci.org/gms1/node-sqlite3-orm/builds/287828472
