### ISSUE TITLE
Expected linebreak to be `LF`

### ISSUE THREAD

**Issue by peterennis** [gms1/node-sqlite3-orm#20]
Running on Windows 10 x64

Ref: #19

![capture200](https://user-images.githubusercontent.com/140737/31368301-c58582ec-ad31-11e7-9251-b8e857de2bed.png)

![capture201](https://user-images.githubusercontent.com/140737/31368390-60d85742-ad32-11e7-9531-91750824b359.png)

**Comment by gms1** [comment]
Hi,
it would have been possible to configure the handling of the line breaks via Git, but now I have also turned off the unnecessary TSLINT rule 'linebreak-style' that caused this garbage
