### ISSUE TITLE
How do I create an app demo?

### ISSUE THREAD

**Issue by peterennis** [gms1/node-sqlite3-orm#25]
I am interested to test further by using the chinook SQLite sample database from here:

```
http://www.sqlitetutorial.net/sqlite-sample-database/
```

I will write a demo sample once I get it working.

What would be the TS class setup just to list employees using node-sqlite3-orm?

![capture205](https://user-images.githubusercontent.com/140737/31572843-d68cd0ba-b063-11e7-8502-b652936b0fbd.png)

**Comment by gms1** [comment]
something like that:
```
@table({name: 'employees', autoIncrement: true})
class Employee {
  @id({name: 'EmployeeId', dbtype: 'INTEGER NOT NULL'})
  employeeId: number;

  @field({name: 'LastName', dbtype: 'TEXT'})
  lastName: string;
}

await new BaseDAO(Employee, sqldb).selectAll();
```

**Comment by gms1** [comment]
closed because of inactivity
