### ISSUE TITLE
OneToMany Relationships

### ISSUE THREAD

**Issue by jo2** [gms1/node-sqlite3-orm#30]
I´m using node-sqlite3-orm for my database and I´m in need of those. Are they already implemented or will they follow in one of the next versions? If they are already implemented how do I use them?

**Comment by gms1** [comment]
an example can be found something hidden in the readme and is shown by means of the 'fk' (foreign key) decorator:

```

@table({name: 'USERS'})
class User {
  @id({name: 'user_id', dbtype: 'INTEGER NOT NULL'})
  userId: number;
....
}

@table({name: 'CONTACTS', autoIncrement: true})
class Contact {
...

  @field({name: 'user_id', dbtype: 'INTEGER NOT NULL'})
  @fk('fk_user_contacts', 'USERS', 'user_id')
  @index('idx_contacts_user')
  userId: number;
}
```

This constraint can then be used to find all of the contacts for a specific user:

```
  let contactsDonald =
      await contactDAO.selectAllOf('fk_user_contacts', User, userDonald);

```

Optionally, the select above can be restricted via an additional sql condition

Related:

```
  // read all users having a contact:
  let allUsersHavingContacts = await userDAO.selectAll(
      'WHERE EXISTS(SELECT 1 FROM CONTACTS C WHERE C.user_id = T.user_id)');
```

please do not hesitate to ask if you require further information and I am also happy to receive suggestions for improvement

**Comment by jo2** [comment]
Ah, ok. I neglected the possibility of doing it in that direction. I thought about giving an user a list of contacts. But that will also work for me. Thanks!

**Comment by gms1** [comment]
you could also map an interface to to a database TEXT field by setting the 'isJson' attribute to true
```
interface JsonData {
  notes: string;
  scores: number[];
}


@table({name: DATATYPE_JSON_TABLE})
class DataTypeJson {
  @id({name: 'id', dbtype: 'INTEGER NOT NULL'})
  id: number;

  @field({name: 'my_json_text', dbtype: 'TEXT', isJson: true})
  myJasonData: JsonData;
}

```
