### ISSUE TITLE
No specs found - npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by peterennis** [gms1/node-sqlite3-orm#42]
Cloned latest:

`npm run test`

![capture333](https://user-images.githubusercontent.com/140737/42073361-0f95f436-7b1b-11e8-9f2b-d7e816e5a797.png)

**Comment by gms1** [comment]
sorry, currently 'npm run build' is required before running the tests
I'm not sure if we should fix that... I actually like it better in the current form, but for JavaScript developers it may be unusual that the project must be built in advance
