### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by peterennis** [gms1/node-sqlite3-orm#44]
Fixed in PR: https://github.com/gms1/node-sqlite3-orm/pull/43

Before:
![capture334](https://user-images.githubusercontent.com/140737/42073525-304bc222-7b1c-11e8-9e17-ef4eba9f10f8.png)

After:
![capture332](https://user-images.githubusercontent.com/140737/42073533-387e6b84-7b1c-11e8-9d31-6b91def8cf50.png)
![capture331](https://user-images.githubusercontent.com/140737/42073542-4056a574-7b1c-11e8-969f-16b1cb1489fd.png)

**Comment by gms1** [comment]
Many thanks; PR merged
