### ISSUE TITLE
empty file created in test

### ISSUE THREAD

**Issue by peterennis** [gms1/node-sqlite3-orm#50]
Ignore.

![capture367](https://user-images.githubusercontent.com/140737/43816473-e11a0d8e-9a89-11e8-8df4-3ab95d95a694.png)

Fixed in this PR: https://github.com/gms1/node-sqlite3-orm/pull/49/commits/8aa8ac8327df4785ebc2d25e7bc4cc014c799475

**Comment by gms1** [comment]
thanks;

btw for easier maintainability I have moved the "GETTING-STARTED.md" to the wiki, please see
https://github.com/gms1/node-sqlite3-orm/wiki/Getting-Started
