### ISSUE TITLE
How to implement Create or Update / REPLACE INTO in DAO?

### ISSUE THREAD

**Issue by drmikecrowe** [gms1/node-sqlite3-orm#73]
Is it possible to implement a [replace into](https://www.sqlitetutorial.net/sqlite-replace-statement/) using  `BaseDAO`?

I know I can query / update or create, but it would be nice if we could use a REPLACE INTO instead of an INSERT INTO

**Comment by gms1** [comment]
basically it is pretty much the same as the `insert into`.
However, the insert behaves differently depending on whether the table uses auto-increment or not.
If auto-increment is used, the primary key column is not specified in the columns clause of the generated insert statement and if a value for the primary key is provided, it will not be bound to any host variable.
I think with a `replace into` statement, such special treatment for auto-increment does not make sense, does it?
So it would be quite easy to implement this, but I cannot promise that I can do it in the near future. PR is of course welcome

**Comment by gms1** [comment]
implemented in 2.5.0
